name: Notify Portfolio Site
on:
  push:
    branches:
      - main # Ajusta se usares 'master'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send Dispatch Event
        run: |
          curl -X POST \
               -H "Accept: application/vnd.github.v3+json" \
               -H "Authorization: token ${{ secrets.SITE_SYNC_TOKEN }}" \
               -d '{"event_type": "writeup_pushed"}' \
               https://api.github.com/repos/diogocoutoooo/diogocoutoooo.github.io/dispatches